### ISSUE TITLE
Convert Manual to Markdown files for Website

### ISSUE THREAD

**Issue by willwade** [dasher-project/website#10]
This is nice and Easy- but time consuming.

Convert this: http://www.inference.org.uk/dasher/download/papers/Manual060125.pdf - To individual chapters for a manual folder to be created here: https://github.com/dasher-project/website/tree/master/content/get-started

**Comment by uukurt** [comment]
I will send a pull request.

**Comment by cagdasgerede** [comment]
@willwade can we close the issue now or is there more work to do?

**Comment by willwade** [comment]
Now we can. Nb. Look at https://github.com/dasher-project/website/commit/9539ece7259ad58d1e51c0e048bf187ac98420fc to see why it wasn’t displaying. There needed to be an index file and a layout like this https://learn.netlify.com/en/cont/pages/
