### ISSUE TITLE
As the user or developer, I want to see the updates as a timeline so that I can understand the history of the project

### ISSUE THREAD

**Issue by willwade** [dasher-project/website#2]
https://dasher-site.netlify.com/about/timeline/ Needs more work. 

Basically taking it from the inference group timeline but could do with more work. If you want access to the spreadsheet that is creating this let me know..

https://docs.google.com/spreadsheets/d/1TdIng-0GGtKYhoEmSRKv-v4eMQjRWAJb61--S6wkbHc/edit#gid=0

**Comment by cagdasgerede** [comment]
Great start! 👍

**Comment by cagdasgerede** [comment]
What is the difference between:
https://dasher-site.netlify.com/
and
https://dasher-web.firebaseapp.com/

**Comment by cagdasgerede** [comment]
I added a row to the spreadsheet but did not update the site. I guess it does not automatically update the web page.

**Comment by willwade** [comment]
The firebase one isn’t constantly updated. Infact it should not work soon (I’ve marked it for deletion) . The netlify one is the one to follow. Any updates on the repo get automated builds by netlify. I just did that firebase one until I got admin rights on our repo.

**Comment by willwade** [comment]
Now looking a bit better in the new layout http://dasher-site.netlify.com/en/history/timeline/

**Comment by gavinhenderson** [comment]
Closing this for now, its not a priority. We can open it at later date
