### ISSUE TITLE
Conversion of Inference pages/Dasher.zone pages to Markdown and new format

### ISSUE THREAD

**Issue by willwade** [dasher-project/website#3]
http://dasher-site.netlify.com/dasher/ 

Is a mirror of the inference group dasher pages. This is really to help move some content over locally while we convert some of the text to the new format and help organise things

**Comment by willwade** [comment]
As @cagdasgerede help needed for this one - its not hard - just time consuming

**Comment by cagdasgerede** [comment]
Can you partition this into smaller chunks as issues? It can be difficult for a contributor to understand what exactly to do?

**Comment by willwade** [comment]
See #5 - that should help. Browsing this a large amount is now in.
