### ISSUE TITLE
Comment: Current roadmap

### ISSUE THREAD

**Issue by willwade** [dasher-project/website#4]
So I've just done a bit of a rebuild. Here's my thinking...

I was thinking about some of @cagdasgerede comments to kick start development and get developers offering help (also chatted to Patrick who helped out on the first round of Google Summer of code who shared same view as @cagdasgerede - hard to get developers learning about this stuff quick enough - and give them some easy routes). So with that in mind who is this site aimed at?

1. Users. yes - we need to make it easy and provide some nice docs on what it is and how it works but really we *know* there are some stumbling blocks to this which we are aiming at fixing (i.e. the UI etc..). So really I suggest the next is more important:...

2. Developers. Make the site super easy to read and use and explain what it is and how to use. Show off the research and how cool this stuff is. :)

I also would like to get all the amazing that content that David et al created in a easier to read format (and update it). I always fear the inference group site may come down one day :( so hence creating a mirror - and moving content over to markdown etc..

So I envisage taking the best bits of dasher.zone and the main inference site and merging it all.. With the aim that developers are right now our key audience. When we get some more development on the go I suggest this site gets remade - and more like a marketing site promoting the software better for end users (and AAC professionals).

**Comment by willwade** [comment]
A couple of other things.. The site is now setup to be multi-lingual and it also has built in search (I can imagine the tips and advice getting more. This will be useful I think!)  - It does need more work. This is really a very quick pull together of the structure and some ideas around layout.  I do want to work on a better home page and I need to reorganise the page structure (its messy). 

It's here for anyone new looking at this stuff. http://dasher-site.netlify.com/en/

And if you want to get involved please do!

**Comment by cagdasgerede** [comment]
There are ~10 college students who wants to contribute. Would you be able to create small tasks related to the web site? The code portion is harder for them to get into without any guidance.

I look forward to hearing from you @willwade

**Comment by cagdasgerede** [comment]
Also, when you say " Patrick who helped out on the first round of Google Summer of code", is this related to Dasher? Was Dasher ever considered for summer of code? I also wonder what the eligibility criteria is. Will check when I get a chance but if you or Patrick know more, I appreciate if you share it here. @willwade

**Comment by willwade** [comment]
Hi @cagdasgerede . Yes. I'm sure @prlw1 told me that they had once been in The GSoC for dasher. Could have my wires crossed there. Eligibility is pretty straightforward  - I had filled in all the application materials earlier this year but pulled out (for a diff project by the way). FYI Its pretty good BUT - as you know - you have to have really manageable chunks of work and you have to have some supervisors who really know the code and know what you are trying to achieve. The work that you are doing to help streamline the coding of dasher will really help.. but It's the knowing the code that bothers me most about dasher in this. (NB: I wonder about a discord server or gitter.im for this kind of chat).
