### ISSUE TITLE
Add content from Inference site

### ISSUE THREAD

**Issue by willwade** [dasher-project/website#5]
Pre-requisties:

1. Have a read of https://learn.netlify.com/en/cont/pages/
2. Install the website locally (see the readme of the project). 

Look at the content at http://inference.org.uk/dasher/ (mirrored https://github.com/dasher-project/website/tree/master/static/dasher )

We need to take as much as the content and populate the markdown pages of the new site from the old Inference site. 

To do this I suggest means doing a couple of things: 
1. Go through the original site. If you find a page that isn't currently in the new site think A) Is this relevant? (i.e. is it meeting notes or just an idea or is actual documentation) - if useful B) "where should this go?". Have a go at putting it in https://github.com/dasher-project/website/tree/master/content - in the correct directory. (It doesn't matter too much - at this stage).
2. Convert the HTML to markdown. You can do this manually - or you can use something like this: http://domchristie.github.io/turndown/
3. Name the file. Give it some a title - and you can weight it if you wish (this tells hugo where to place it in the menu system). Have a look at https://raw.githubusercontent.com/dasher-project/website/master/content/research/presentations.md - to get an idea of the format of the file.

**Comment by bilgesubuk** [comment]
I will send a pull request

**Comment by bilgesubuk** [comment]
#18
