### ISSUE TITLE
Update/Add Linux Install Instructions

### ISSUE THREAD

**Issue by willwade** [dasher-project/website#7]

**Comment by mabasturk** [comment]
I will send a pull request

**Comment by cagdasgerede** [comment]
@mabasturk 

You can convert the google doc (https://docs.google.com/document/d/1qosKPV0GXbHs69PyvK9BR3S3oNgdV8il7AVfO1M4Fh4
) referenced in README into the markdown format.

Also, checout .travis.yml file for the steps to install dependencies.

**Comment by gavinhenderson** [comment]
Closing this as we no longer maintain this version of dasher
