### ISSUE TITLE
Update/Add instructions for Java install

### ISSUE THREAD

**Issue by willwade** [dasher-project/website#8]

**Comment by samilkahraman** [comment]
I will send a pull request.

**Comment by cagdasgerede** [comment]
Samil,

There is a pull request (https://github.com/dasher-project/dasher/pull/139) for java continuous integration set up and you should include the usage of gradle for the instructions. So wait for the pull request to be merged to finalize your instructions.

**Comment by gavinhenderson** [comment]
Closing this because we no longer maintain the fork of dasher (gnome version)
